added DAO implementation
oroboro-cpu/jv-create-annotation pull request #1
Opened 2021-01-07 20:29 UTC by oroboro-cpu

2021-01-07 21:05 UTC, YuraBondarenko approved these changes

2021-01-08 09:26 UTC, KseniiaMakarova requested changes

2021-01-08 09:26 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +        BetDao betDao = new BetDaoImpl();
let's have this dependency as a field

2021-01-08 09:26 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            }
can we use only one catch block? the messages are pretty the same

2021-01-08 09:26 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            betDao.add(bet);
let’s save  the bet if it is not null

2021-01-08 09:26 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            System.out.println(bet == null ? null : bet.toString());
```suggestion
            System.out.println(bet);
```

2021-01-08 09:26 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/UserDaoImpl.java
> +
redundant empty line

2021-01-08 09:26 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/model/Bet.java
> +        return "model.Bet{"
```suggestion
        return "Bet{"
```

2021-01-08 14:20 UTC, KseniiaMakarova approved these changes

2021-01-10 15:55 UTC, merged